name: Kind Test

on:
  workflow_dispatch:
    inputs:
      kindVersion:
        description: The kind version
        default: 0.20.0 # Kubernetes version: 1.27.X
      runTests:
        description: The regex passed to the -run option of `go test`
        default: "^TestAcc"
      terraformVersion:
        description: Terraform version
        default: 1.5.6
      parallelRuns:
        description: The maximum number of tests to run simultaneously
        default: 8
      pull_request:
        branches:
         - main

env:
  KIND_VERSION: ${{ github.event.inputs.kindVersion || vars.KIND_VERSION }}

jobs:
  kind_test:
    - name: Setup kind
        uses: helm/kind-action@fa81e57adff234b2908110485695db0f181f3c67 # v1.7.0
        with:
          wait: 2m
          version: v${{ env.KIND_VERSION }}
          config: .github/config/kind_test_config.yaml